### PR TITLE
CCH 492: Remove need for PyCsw when publishing/reading metadata.

### PR DESCRIPTION
**Pull request by dpattermann-usgs**
Removed need for PyCsw when reading metadata.
Metadata should be returned as GSON in a map with keys: Keywords, Box, Resources.

### CODE REVIEW

**Comment by zmoore-usgs** [comment]
I think those docker keystores are supposed to still be included? I can't do a docker-compose up with the local profile because those are gone, unless we're supposed to generate our own keystores - which I could do.

AQCU and MLR come bundled with keystores for their local development stuff so I think it would be okay for CCH to as well?

**Comment by dpattermann-usgs** [comment]
@zmoore-usgs Does it work for you now?

**Comment by zmoore-usgs** [comment]
Re-pulling and testing now

**Comment by zmoore-usgs** [comment]
All good now, thanks!

**Comment by dpattermann-usgs** [comment]
Wrote a test for extractStringsFromCswDoc to alert us if it breaks. Will merge after checks are made.

**Comment by dpattermann-usgs** [comment]
I cleaned up some of the errors coming from Codacy, going to merge now.

**Pull request merged**
