### PR TITLE
Updated KeyCloak to version 8.0.2

### PR DESCRIPTION
**Pull request by zmoore-usgs**

### CODE REVIEW

**Comment by mhines-usgs** [comment]
@zmoore-usgs can you try pushing your master here to this branch? I'm getting some merge conflicts when I pull this and even after resolving those I'm still getting that curl issue, so not sure if that would clear all those things up or if I should resolve that locally too?

**Comment by zmoore-usgs** [comment]
Huh, weird. Yeah I can do that

**Comment by zmoore-usgs** [comment]
Okay, should be up to date now

**Comment by mhines-usgs** [comment]
Works fine for me locally!

**Comment by zmoore-usgs** [comment]
:+1:

**Pull request merged**
