### PR TITLE
mediation page makeover

### PR DESCRIPTION
**Pull request by mwernimont**
@zmoore-usgs or @thongsav-usgs  hows it look to you?
Tested it on Chrome, FireFox, and Safari, and an ipad, the layout looked the same on all of them. Hopefully, the shifting of content didn't break any functionality.

### CODE REVIEW

**Comment by zmoore-usgs** [comment]
Code changes look good to me. I'll pull down the changes and test the functionality locally

**Comment by mhines-usgs** [comment]
Ah I didn't think about the potential for expanding resources darn.. @zmoore-usgs, good call.

I guess moving the metadata section to the bottom left is better since the keywords would probably suffer from the same problem.. Then because it'd be left-heavy, move titles/descriptions above the bounding box/keywords panel? What do you guys think of that?

**Comment by mwernimont** [comment]
@mhines-usgs So move metadata underneath titles/descriptions?

**Comment by mhines-usgs** [comment]
I would say switch columns and locations for titles/descriptions and metadata. That way metadata is at the bottom of the left column and bounding boxes and keywords are at the bottom of the right column. Both of those have a potentially infinite length?

**Comment by zmoore-usgs** [comment]
@mhines-usgs @mwernimont Would there be a way to make it ordered in the way that each step needs to be completed? II.E: I think the order of steps is roughly:

1). Create item
2). Create Layer
3). Populate Services from Layer
4). Select Item Type & Attribute
5). Populate Metadata
5). Titles/Descriptions, Thumbnail, and Resources

So maybe something like:

Item ID     | Tumbnail 
Services    | Titles / Descriptions
Item Type | Resources
Metadata  |

Thoughts? It's okay if you guys disagree, just a thought. Then the flow is go down the left side and then go down the right side. Maybe even number each box so that it is clear what the order needs to be?

**Comment by mwernimont** [comment]
Talked to @mhines-usgs and decided to just have the possible ever expanding options (Resources Keywords) on the bottom of the either column. 

Bueno?

**Comment by mhines-usgs** [comment]
Yeah, that's good. Can you also edit out the validation part for download file name that @zmoore-usgs mentioned? I forgot about that. We don't need that anymore too. Thank you!

**Comment by mwernimont** [comment]
@zmoore-usgs that was the correct code block to remove right? Hopefully our IDE's line up the code the same.

**Comment by zmoore-usgs** [comment]
@mwernimont Yep, looks good to me. I'll pull down the changes and test it out again real quick but then I think this should be good to go.

**Pull request merged**
