### PR TITLE
CCHS-444: Allow management of NHC NOAA layers for RTS outside of software release 

### PR DESCRIPTION
**Pull request by zmoore-usgs**
Note that this will also require context.xml changes on the portal tomcat before it is deployed. I will make those changes on DEV once this PR has been approved.

New context.xml variables for NHC Track default values (all values are optional, missing values will be blank), see `coastal-hazards-portal/docker/context.xml` for the current default values for these variables:

coastal-hazards.nhc.track.bbox.north - Numeric (cast from String)
coastal-hazards.nhc.track.bbox.west - Numeric (cast from String)
coastal-hazards.nhc.track.bbox.east - Numeric (cast from String)
coastal-hazards.nhc.track.bbox.south - Numeric (cast from String)
coastal-hazards.nhc.track.wms - String
coastal-hazards.nhc.track.attrs - String
coastal-hazards.nhc.track.attr.params - String
coastal-hazards.nhc.track.tiny.text - String
coastal-hazards.nhc.track.med.title - String
coastal-hazards.nhc.track.med.text - String
coastal-hazards.nhc.track.full.title - String
coastal-hazards.nhc.track.full.text - String
coastal-hazards.nhc.track.keywords -String
coastal-hazards.nhc.track.data.titles - String
coastal-hazards.nhc.track.data.links - String
coastal-hazards.nhc.track.pub.titles - String
coastal-hazards.nhc.track.pub.links - String
coastal-hazards.nhc.track.res.titles - String
coastal-hazards.nhc.track.res.links - String

### CODE REVIEW

**Comment by mhines-usgs** [comment]
Pulling this down to check out locally.

**Comment by mhines-usgs** [comment]
- easily able to make a storm, and modify bbox as desired

**Comment by mhines-usgs** [comment]
@zmoore-usgs if Kathy doesn't get to this before tomorrow, are you OK demo-ing locally? Or should we merge and put on dev before Kathy reviews?

**Comment by zmoore-usgs** [comment]
I think we could probably merge tomorrow morning and Kathy could review post-merge if she hasn't had time before then. I'm guessing it would be good to have it able to be tested by the coops as soon as possible after demoing because it could be a bit confusing to figure out if they can't poke around on it soon after the demo.

**Comment by mhines-usgs** [comment]
Ok, that sounds good and I agree, it's weird to give a demo if it's not available to play with.

**Pull request merged**
