### PR TITLE
Events for js

### PR DESCRIPTION
**Pull request by jread-usgs**
@isuftin should be able to do this:
```
addMoreTrg.addEventListener('mySpecialEvent',function(){
  addMoreTrg.beginElement();
},false);
```
for `addMoreTrg`, `addFirstTrg`, `dumpBucketTrg`, `openBucketTrg`, and `closeBucketTrg`

### CODE REVIEW

**Comment by jread-usgs** [comment]
@isuftin did you pull from my branch to get this?

**Comment by isuftin** [comment]
@jread-usgs So this is pretty much the best thing ever :smile:

**Comment by jread-usgs** [comment]
thanks buuuuddy

**Comment by jread-usgs** [comment]
:dancers:

**Pull request merged**
