### PR TITLE
Updates for security

### PR DESCRIPTION
**Pull request by mhines-usgs**

### CODE REVIEW

**Comment by isuftin** [comment]
This looks right, but have you tested locally that uploading still works as expected?

**Comment by isuftin** [comment]
Also that layer sweeping is still happening

**Comment by mhines-usgs** [comment]
Working on testing the changes in 🐳 right 😸

**Comment by mhines-usgs** [comment]
- [ ] can still upload shapefiles and create new data

- [ ] can still run layer sweep utilities

**Comment by mhines-usgs** [comment]
@isuftin the layer sweep utils still work as does the portal with the changes here.

**Comment by isuftin** [comment]
👍 :shipit:

**Pull request merged**
